### ISSUE TITLE
Make this into React app

### ISSUE THREAD

**Issue by naman-ng** [naman-ng/Odyssey-23#1]
Simply convert this into a react app without changing the UI/UX

**Comment by naman-ng** [comment]
Great!! Please go on.

**Comment by naman-ng** [comment]
> hey naman, i think i can do this

Assigned this to you

**Comment by janmesh799** [comment]
Great ✌️

**Comment by janmesh799** [comment]
i have made a PR regarding the issue
check it out

**Comment by naman-ng** [comment]
Thanks @janmesh799 for resolving this.
